language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
env:
    - TOXENV=django-2.2
    - TOXENV=django-3.0
    - TOXENV=django-3.1
    - TOXENV=django-3.2

install:
  - pip install tox

script: tox
