---
name: Test

on:
  push:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

        django:
          - "2.2"
          - "3.0"
          - "3.1"
          - "3.2"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install Django==${{ matrix.django }} django-ipware
          pip install coveralls pytest pytest-cov pytest-django pytest-flake8 pytest-pythonpath
      - name: Run tests
        run: |
          py.test tests/ --cov=admin_honeypot --cov-config=.coveragerc --cov-report=term-missing --flake8 admin_honeypot
      # https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
      - name: Report coverage results to Coveralls
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: run-python${{ matrix.python }}-django${{ matrix.django }}
          COVERALLS_PARALLEL: true

  # https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
  finish-coverage:
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finish Coveralls reporting
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
